version: '3'

services:
  api:
    build: .
    depends_on:
      - mysql_server
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/scr/app
      #- ./:/usr/scr/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=mysql_server
      - DATABASE_PORT=3306
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=fastapi_app
      - DATABASE_USERNAME=root
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60

  mysql_server:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=fastapi_app
    volumes:
      - mysql-db:/var/lib/mysql


volumes:
  mysql-db: